variables:
  GOFLAGS: '-mod=vendor'

after_script:
  - docker logout docker.io


build image:
  stage: build
  script:
    - docker build -t avenga/couper:$CI_COMMIT_SHORT_SHA .
  except:
    - master
    - develop
    - tags

build and push image:
  stage: push
  script:
    - docker login -u serverteam --password-stdin docker.io < $DOCKER_CREDS
    - docker build -t avenga/couper:$CI_COMMIT_SHORT_SHA .
    - docker push avenga/couper:$CI_COMMIT_SHORT_SHA
  only:
    - master
    - tags
    - develop
  when: manual

push tag:
  stage: push
  script:
    - docker pull avenga/couper:$CI_COMMIT_SHORT_SHA
    - docker tag avenga/couper:$CI_COMMIT_SHORT_SHA avenga/couper:$CI_COMMIT_REF_NAME
    - docker login -u serverteam --password-stdin docker.io < $DOCKER_CREDS
    - docker push avenga/couper:$CI_COMMIT_REF_NAME
  only:
    - tags
  when: manual

push latest:
  stage: push
  script:
    - docker pull avenga/couper:$CI_COMMIT_SHORT_SHA
    - docker tag avenga/couper:$CI_COMMIT_SHORT_SHA avenga/couper:latest
    - docker login -u serverteam --password-stdin docker.io < $DOCKER_CREDS
    - docker push avenga/couper:latest
  only:
    - tags
  when: manual


tests:
  stage: test
  image: 'golang:1.14'
  script:
    - go test -v -short -race -timeout 30s ./...

stages:
  - test
  - build
  - push
