building couper:
  stage: build
  image: 'golang:1.14'
  variables:
    GOFLAGS: '-mod=vendor'
  before_script:
    - go version
  script:
    - go build -v main.go

tests:
  stage: test
  image: 'golang:1.14'
  variables:
    GOFLAGS: '-mod=vendor'
  script:
    - go test -v -short -race -timeout 30s ./...

stages:
  - test
  - build
