variables:
  GOFLAGS: '-mod=vendor'

build:
  stage: build
  script:
    - docker build -t avenga/couper:$CI_COMMIT_SHORT_SHA .

tests:
  stage: test
  image: 'golang:1.14'
  script:
    - go test -v -short -race -timeout 30s ./...

stages:
  - test
  - build
