variables:
  GOFLAGS: '-mod=vendor'

build image:
  stage: build
  script:
    - docker build -t avenga/couper:$CI_COMMIT_SHORT_SHA .
    - mkdir artifacts
    - docker save avenga/couper:$CI_COMMIT_SHORT_SHA -o artifacts/image.tar
  artifacts:
    paths:
      - artifacts

push tag:
  stage: push
  script:
    - docker load -i artifacts/image.tar
    - docker tag avenga/couper:$CI_COMMIT_SHORT_SHA avenga/couper:$CI_COMMIT_REF_NAME
    - docker login -u serverteam --password-stdin docker.io < $DOCKER_CREDS
    - docker push avenga/couper:$CI_COMMIT_REF_NAME
  after_script:
    - docker logout docker.io
  only:
    - tags

push latest:
  stage: push
  script:
    - docker load -i artifacts/image.tar
    - docker tag avenga/couper:$CI_COMMIT_SHORT_SHA avenga/couper:latest
    - docker login -u serverteam --password-stdin docker.io < $DOCKER_CREDS
    - docker push avenga/couper:latest
  after_script:
    - docker logout docker.io
  only:
    - master


tests:
  stage: test
  image: 'golang:1.14'
  script:
    - go test -v -short -race -timeout 30s ./...

stages:
  - test
  - build
  - push
