version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    hostname: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Zipkin
  zipkin-all-in-one:
    hostname: zipkin-all-in-one
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  # Collector
  otel-collector:
    image: 'otel/opentelemetry-collector-contrib-dev:latest'
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - $PWD/telemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317"        # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one

  couper:
    build:
      dockerfile: $PWD/Dockerfile
      context: $PWD
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
#      - OTA_EXPORTER_JAEGER_ENDPOINT
#      - OTA_EXPORTER_JAEGER_SERVICE_NAME
#      - OTA_EXPORTER_ZIPKIN_ENDPOINT
#      - OTA_EXPORTER_ZIPKIN_SERVICE_NAME
      - USER=dev-docker # fromEnv filled attrs
      - COUPER_WATCH=true
      - COUPER_TELEMETRY_TRACES=true
      - COUPER_TELEMETRY_METRICS=true
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - $PWD/telemetry/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
