name: Daily-Fuzz

on:
  schedule:
    - cron: '* 9,15 * * *'
  workflow_dispatch:

jobs:

  fuzz:
    name: fuzz
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
        id: go
      - run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: fuzz-results
          path: fuzz/server
        continue-on-error: true # may not exist on first run or previous upload err

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: fuzz/server

      - name: install go-fuzz
        run: go get -u github.com/dvyukov/go-fuzz/go-fuzz github.com/dvyukov/go-fuzz/go-fuzz-build
      - name: vendor go-fuzz
        run: go mod vendor && git clone https://github.com/dvyukov/go-fuzz.git vendor/github.com/dvyukov/go-fuzz

      - name: fuzz-simple-server
        run: cd fuzz/server && go-fuzz-build && go-fuzz

      - uses: actions/upload-artifact@v2
        with:
          name: fuzz-results
          path: |
            fuzz/server/corpus
            fuzz/server/crashers
            fuzz/server/suppressions
            !fuzz/**/*.zip
          if-no-files-found: warn
          retention-days: 14
