name: Docker

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Test and build container image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '1.14'
      id: go
    - run: go version

    - name: checkout
      uses: actions/checkout@v2

    - name: Test
      run: go test -v -timeout 30s -race ./...

    - name: Build and push docker image
      # Recommended to refer to an explicit sha in combination with secrets
      uses: docker/build-push-action@85d408708d8c09e8991e7b18899e77d7aee89287 #v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: avenga/couper
        tag_with_ref: true
        add_git_labels: true
